server:
  port: 8117
spring:
  application:
    name: java17_demo
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test1
    username: root
    password: 123456